name: sonify
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.3  # https://anaconda.org/conda-forge/ffmpeg
  - obspy
  - pip
  - setuptools<58.4.0  # https://github.com/pypa/setuptools/issues/2497
  - tqdm
# Lines above should be IDENTICAL to environment.yml
  - black
  - ipython
  - isort
  - pytest-cov
  - pytest-mpl
  - pip:
    - --requirement doc/requirements.txt
    - --editable .
