name: sonify
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.3  # https://anaconda.org/conda-forge/ffmpeg
  - obspy
  - pip
  - setuptools<58.4.0  # https://github.com/pypa/setuptools/issues/2497
  - pip:
    - --editable .
